# Generated by Django 5.0.2 on 2024-12-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='picture',
        ),
    ]
