# Generated by Django 5.0.2 on 2024-12-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_myuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to='accounts/y/m/%d'),
        ),
    ]
