# Generated by Django 5.0.2 on 2024-12-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.myuser'),
        ),
    ]
