# Generated by Django 5.0.2 on 2024-12-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_myuser_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='following',
            field=models.ManyToManyField(to='accounts.myuser'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='followers',
            field=models.ManyToManyField(to='accounts.myuser'),
        ),
    ]
