# Generated by Django 5.0.2 on 2025-01-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_myuser_following_alter_myuser_followers'),
        ('admin', '0004_alter_logentry_user'),
        ('posts', '0002_alter_comment_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='CustomUser',
        ),
    ]
