# Generated by Django 5.0.2 on 2024-11-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarian',
            old_name='Library',
            new_name='library',
        ),
    ]
